<?xml version="1.0" encoding="UTF-8"?>
<!--Revision 05-->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:pain.002.001.10" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:pain.002.001.10">
	<xs:element name="Document" type="Document"/>
	<xs:simpleType name="ActiveOrHistoricCurrencyAndAmount_SimpleType">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="5"/>
			<xs:totalDigits value="18"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ActiveOrHistoricCurrencyAndAmount">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">ActiveOrHistoricCurrencyAndAmount</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">A number of monetary units specified in an active or a historic currency where the unit of currency is explicit and compliant with ISO 4217.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ფულადი ერთეულების რაოდენობა, მითითებული მოქმედ ან ისტორიულ ვალუტაში, სადაც ვალუტის ერთეული ცალსახად არის განსაზღვრული და შეესაბამება ISO 4217-ს.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="ActiveOrHistoricCurrencyAndAmount_SimpleType">
				<xs:attribute name="Ccy" type="ActiveOrHistoricCurrencyCode" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="ActiveOrHistoricCurrencyCode">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">ActiveOrHistoricCurrencyCode</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ვალუტისთვის საერთაშორისო იდენტიფიკაციის სქემის ფარგლებში მხარდამჭერი სააგენტოს მიერ მინიჭებული კოდი, როგორც აღწერილია საერთაშორისო სტანდარტის ISO 4217 „ვალუტებისა და ფონდების წარმოდგენის კოდები“ უახლეს გამოცემაში.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3,3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GEO_BICFIDec2014Identifier">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_BICFIDec2014Identifier</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362: 2014 - "Banking - Banking telecommunication messages - Business identifier code (BIC)".</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ISO 9362 რეგისტრაციის ორგანოს მიერ ფინანსური ინსტიტუტისთვის მინიჭებული კოდი, როგორც აღწერილია ISO 9362:2014-ში — „საბანკო საქმე — საბანკო სატელეკომუნიკაციო შეტყობინებები — ბიზნეს იდენტიფიკატორის კოდი (BIC)“.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]{4,4}GE[A-Z0-9]{2,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GEO_BranchAndFinancialInstitutionIdentification6">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_BranchAndFinancialInstitutionIdentification6</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution or a branch of a financial institution.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ფინანსური ინსტიტუტის ან ფინანსური ინსტიტუტის ფილიალის უნიკალური და ერთმნიშვნელოვანი იდენტიფიკაცია.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="FinInstnId" type="GEO_FinancialInstitutionIdentification18">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">FinancialInstitutionIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a financial institution, as assigned under an internationally recognised or proprietary identification scheme.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ფინანსური ინსტიტუტის უნიკალური და ერთმნიშვნელოვანი იდენტიფიკაცია, მინიჭებული საერთაშორისო აღიარებული ან საკუთარი იდენტიფიკაციის სქემის ფარგლებში.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_Charges7">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_Charges7</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Provides information on the charges related to the payment transaction.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">გადარიცხვის ტრანზაქციასთან დაკავშირებული საკომისიოების შესახებ ინფორმაცია.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Amt" type="ActiveOrHistoricCurrencyAndAmount">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Transaction charges to be paid by the charge bearer.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Agt" type="GEO_BranchAndFinancialInstitutionIdentification6">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">Agent</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Agent that takes the transaction charges or to which the transaction charges are due.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_ClearingSystemMemberIdentification2">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_ClearingSystemMemberIdentification2</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by a clearing system, to unambiguously identify a member of the clearing system.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">კლირინგის სისტემის მიერ მინიჭებული უნიკალური იდენტიფიკაცია, რომელიც ცალსახად განსაზღვრავს კლირინგის სისტემის წევრს.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="MmbId" type="GEO_BICFIDec2014Identifier">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">MemberIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Identification of a member of a clearing system.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">კლირინგის სისტემის წევრის იდენტიფიკაცია.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_CustomerPaymentStatusReportV10">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">CustomerPaymentStatusReportV10</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">
				Scope&#13;
				The CustomerPaymentStatusReport message is sent by an instructed agent to the previous party in the payment chain. It is used to inform this party about the positive or negative status of an instruction (either single or file). It is also used to report on a pending instruction.&#13;
				Usage&#13;
				The CustomerPaymentStatusReport message is exchanged between an agent and a non-financial institution customer to provide status information on instructions previously sent. Its usage will always be governed by a bilateral agreement between the agent and the non-financial institution customer.&#13;
				The CustomerPaymentStatusReport message can be used to provide information about the status (for example a rejection, an acceptance) of the initiation of a credit transfer, a direct debit, as well as on the initiation of other customer instructions.&#13;
				The CustomerPaymentStatusReport message refers to the original instruction(s) by means of references only or by means of references and a set of elements from the original instruction.&#13;
				The CustomerPaymentStatusReport message can be used in domestic and cross-border scenarios.&#13;
				The CustomerPaymentStatusReport may also be sent to the receiver of the payment in a real time payment scenario, as both sides of the transactions must be informed of the status of the transaction (that is either the beneficiary is credited, or the transaction is rejected).
			</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">
				საზღვრები
				CustomerPaymentStatusReport შეტყობინება იგზავნება ინსტრუქტირებულმა აგენტმა გადახდის ჯაჭვის წინა მხარეს. ის გამოიყენება იმისთვის, რომ აცნობოს ამ მხარეს ინსტრუქციის (ერთჯერადი ან ფაილის) დადებითი ან უარყოფითი სტატუსის შესახებ. ის ასევე გამოიყენება პენდინგ ინსტრუქციის შესახებ ანგარიშის გასაკეთებლად.
				გამოყენება
				CustomerPaymentStatusReport შეტყობინება გაცვლილია აგენტსა და არასაფინანსო დაწესებულების კლიენტს შორის, რათა მიაწოდოს სტატუსის ინფორმაცია ადრე გაგზავნილ ინსტრუქციებზე. მისი გამოყენება ყოველთვის იქნება რეგულირებული აგენტსა და არასაფინანსო დაწესებულების კლიენტს შორის ორმხრივი შეთანხმებით.
				CustomerPaymentStatusReport შეტყობინება შეიძლება გამოყენებულ იქნას ინფორმაციის მიწოდებისთვის სტატუსის შესახებ (მაგალითად, უარყოფა, მიღება) კრედიტ ტრანსფერის ინიციირების, პირდაპირი დებეტის, ასევე სხვა მომხმარებლის ინსტრუქციების ინიციირების შესახებ.
				CustomerPaymentStatusReport შეტყობინება ეხება ორიგინალური ინსტრუქციების მითითებებს მხოლოდ მითითებების საშუალებით ან მითითებების საშუალებით და ორიგინალური ინსტრუქციის ელემენტების ნაკრებით.
				CustomerPaymentStatusReport შეტყობინება შეიძლება გამოყენებულ იქნას საშინაო და საზღვარგარეთ სცენარებში.
				CustomerPaymentStatusReport ასევე შეიძლება გაიგზავნოს გადახდის მიმღებს რეალურ დროში გადახდის სცენარში, რადგან ორივე მხარეს უნდა ჰქონდეს ინფორმაცია ტრანზაქციის სტატუსის შესახებ (რომელიც არის ან ბენეფიციარი კრედიტდება, ან ტრანზაქცია უარყოფილია).
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="GrpHdr" type="GEO_GroupHeader86">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">GroupHeader</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Set of characteristics shared by all individual transactions included in the message.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">მხოლოდ ამ შეტყობინებაში ჩართული ყველა ინდივიდუალური ტრანზაქციის მიერ გაზიარებული მახასიათებლების ნაკრები.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OrgnlGrpInfAndSts" type="GEO_OriginalGroupHeader17">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalGroupInformationAndStatus</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Original group information concerning the group of transactions, to which the status report message refers to.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ჯგუფის ინფორმაცია ტრანზაქციების ჯგუფის შესახებ, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="OrgnlPmtInfAndSts" type="GEO_OriginalPaymentInstruction32">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalPaymentInformationAndStatus</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Information concerning the original payment information, to which the status report message refers.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური გადახდის ინფორმაციის შესახებ ინფორმაცია, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="CstmrPmtStsRpt" type="GEO_CustomerPaymentStatusReportV10">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">CustomerPaymentStatusReport</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Customer Payment Status Report message.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">კლიენტის გადახდის სტატუსის ანგარიშის შეტყობინება.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ExternalPaymentGroupStatus1Code">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExternalPaymentTransactionStatus1Code">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">ExternalPaymentTransactionStatus1Code</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">
				Specifies the status of an individual payment instructions, as published in an external payment transaction status code set.&#13;
				External code sets can be downloaded from www.iso20022.org.
			</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">
				ინდივიდუალური გადახდის ინსტრუქციის სტატუსი, როგორც გამოქვეყნებულია გარე გადახდის ტრანზაქციის სტატუსის კოდების ნაკრებში.&#13;
				გარე კოდების ნაკრები ხელმისაწვდომია www.iso20022.org-ზე.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExternalStatusReason1Code">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">ExternalStatusReason1Code</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">
				Specifies the status reason, as published in an external status reason code list.&#13;
				External code sets can be downloaded from www.iso20022.org.
			</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">
				სტატუსის მიზეზი, როგორც გამოქვეყნებულია გარე სტატუსის მიზეზის კოდების სიაში.&#13;
				გარე კოდების სეტები ხელმისაწვდომია www.iso20022.org-ზე.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GEO_FinancialInstitutionIdentification18">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_FinancialInstitutionIdentification18</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Specifies the details to identify a financial institution.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">მოიცავს ფინანსური ინსტიტუტის იდენტიფიკაციისთვის საჭირო დეტალებს.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="1" name="BICFI" type="GEO_BICFIDec2014Identifier">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">BICFI</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Code allocated to a financial institution by the ISO 9362 Registration Authority as described in ISO 9362 "Banking - Banking telecommunication messages - Business identifier code (BIC)".</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ISO 9362 რეგისტრაციის ორგანოს მიერ ფინანსური ინსტიტუტისთვის მინიჭებული კოდი, როგორც აღწერილია ISO 9362-ში „საბანკო საქმე — საბანკო სატელეკომუნიკაციო შეტყობინებები — ბიზნეს იდენტიფიკატორის კოდი (BIC)“.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="ClrSysMmbId" type="GEO_ClearingSystemMemberIdentification2">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">ClearingSystemMemberIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Information used to identify a member within a clearing system.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ინფორმაცია, რომელიც გამოიყენება კლირინგის სისტემაში წევრის იდენტიფიკაციისთვის.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_GroupHeader86">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_GroupHeader86</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Set of characteristics shared by all individual transactions included in the message.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">მხოლოდ ამ შეტყობინებაში ჩართული ყველა ინდივიდუალური ტრანზაქციის მიერ გაზიარებული მახასიათებლების ნაკრები.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="MsgId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">MessageIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Point to point reference, as assigned by the instructing party, and sent to the next party in the chain to unambiguously identify the message.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">მიმართულების წერტილის რეფერენსი, რომელიც მინიჭებულია ინსტრუქტორის მიერ და გადაეცემა შემდეგ მხარეს, რათა ცალსახად განსაზღვროს შეტყობინება.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CreDtTm" type="GEO_ISODateTime">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">CreationDateTime</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Date and time at which the message was created.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">შეტყობინების შექმნის თარიღი და დრო.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="GEO_ISODateTime">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_ISODateTime</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:dateTime">
			<xs:pattern value=".*(\+|-)((0[0-9])|(1[0-3])):[0-5][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GEO_RestrictedFINXMax105Text_Ka">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_RestrictedFINXMax105Text_Ka</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a minimum length of 1, and a maximum length of 105 characters, and limited to character set X, that is, 0-9 a-z A-Z / - ? : ( ) . , ‘ + .</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">განსაზღვრავს სიმბოლოთა სტრიქონს მინიმალური სიგრძით 1 და მაქსიმალური სიგრძით 105 სიმბოლო, და შეზღუდულია სიმბოლოების ნაკრებით X, ანუ 0-9 a-z A-Z / - ? : ( ) . , ‘ + .</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9a-zA-Zა-ჰ/\-\?:\(\)\.,'\+ ]+"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="105"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GEO_RestrictedFINXMax35Text">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_RestrictedFINXMax35Text</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a minimum length of 1, and a maximum length of 35 characters, and limited to character set X, that is, 0-9 a-z A-Z / - ? : ( ) . , ‘ + .</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">განსაზღვრავს სიმბოლოთა სტრიქონს მინიმალური სიგრძით 1 და მაქსიმალური სიგრძით 35 სიმბოლო, და შეზღუდულია სიმბოლოების ნაკრებით X, ანუ 0-9 a-z A-Z / - ? : ( ) . , ‘ + .</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9a-zA-Z/\-\?:\(\)\.,'\+ ]+"/>
			<xs:minLength value="1"/>
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GEO_OriginalGroupHeader17">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_OriginalGroupHeader17</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Original group information concerning the group of transactions, to which the status report message refers to.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ჯგუფის ინფორმაცია ტრანზაქციების ჯგუფის შესახებ, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OrgnlMsgId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalMessageIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original sending party, to unambiguously identify the original message.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური შეტყობინების უნიკალური იდენტიფიკაცია, რომელიც მინიჭებულია ორიგინალური გამგზავნის მიერ, რათა ცალსახად განსაზღვროს ორიგინალური შეტყობინება.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OrgnlMsgNmId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalMessageNameIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Specifies the original message name identifier to which the message refers.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">მიუთითებს ორიგინალური შეტყობინების სახელის იდენტიფიკატორს.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="GrpSts" type="ExternalPaymentGroupStatus1Code">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">GroupStatus</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Specifies the status of a group of transactions.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ტრანზაქციების ჯგუფის სტატუსი.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="4" minOccurs="0" name="StsRsnInf" type="StatusReasonInformation12">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">StatusReasonInformation</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Provides detailed information on the status reason.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">სტატუსის მიზეზის შესახებ დეტალური ინფორმაცია.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_OriginalPaymentInstruction32">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_OriginalPaymentInstruction32</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Information concerning the original payment information, to which the status report message refers.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ორიგინალური გადახდის ინფორმაციის შესახებ ინფორმაცია, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OrgnlPmtInfId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalPaymentInformationIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original sending party, to unambiguously identify the original payment information group.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური გადახდის ინფორმაციის უნიკალური იდენტიფიკაცია, რომელიც მინიჭებულია ორიგინალური გამგზავნის მიერ, რათა ცალსახად განსაზღვროს ორიგინალური გადახდის ინფორმაციის ჯგუფი.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="1" name="TxInfAndSts" type="GEO_PaymentTransaction105">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">TransactionInformationAndStatus</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Provides information on the original transactions to which the status report message refers.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ტრანზაქციის შესახებ ინფორმაცია, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_PaymentTransaction105">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_PaymentTransaction105</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Provides information on the original transactions to which the status report message refers.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ტრანზაქციის შესახებ ინფორმაცია, რომლის სტატუსის ანგარიშის შეტყობინება ეხება.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="0" name="StsId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">StatusIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">
						Unique identification, as assigned by an instructing party for an instructed party, to unambiguously identify the reported status.
						Usage: The instructing party is the party sending the status message and not the party that sent the original instruction that is being reported on.
					</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">
						უნიკალური იდენტიფიკაცია, რომელიც მინიჭებულია ინსტრუქტორის მიერ ინსტრუქტირებულისთვის, რათა ცალსახად განსაზღვროს შეტყობინებული სტატუსი.
						გამოყენება: ინსტრუქტორი არის მხარე, რომელიც აგზავნის სტატუსის შეტყობინებას და არა მხარე, რომელმაც გააგზავნა ორიგინალური ინსტრუქცია, რომლის შესახებაც შეტყობინება გაკეთდა.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="OrgnlInstrId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalInstructionIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original instructing party for the original instructed party, to unambiguously identify the original instruction.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ინსტრუქციის უნიკალური იდენტიფიკაცია, რომელიც მინიჭებულია ორიგინალური ინსტრუქტორის მიერ ორიგინალური ინსტრუქტირებული მხარისთვის, რათა ცალსახად განსაზღვროს ორიგინალური ინსტრუქცია.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OrgnlEndToEndId" type="GEO_RestrictedFINXMax35Text">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalEndToEndIdentification</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Unique identification, as assigned by the original initiating party, to unambiguously identify the original transaction.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ორიგინალური ტრანზაქციის უნიკალური იდენტიფიკაცია, რომელიც მინიჭებულია ორიგინალური ინიციატორის მიერ, რათა ცალსახად განსაზღვროს ორიგინალური ტრანზაქცია.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OrgnlUETR" type="UUIDv4Identifier">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">OriginalUETR</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Universally unique identifier to provide the original end-to-end reference of a payment transaction.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">უნივერსალურად უნიკალური იდენტიფიკატორი, რომელიც უზრუნველყოფს გადახდის ტრანზაქციის ორიგინალური end-to-end რეფერენსის მიწოდებას.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TxSts" type="ExternalPaymentTransactionStatus1Code">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">TransactionStatus</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Specifies the status of a transaction, in a coded form.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">ტრანზაქციის სტატუსი კოდირებული ფორმით.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="4" minOccurs="0" name="StsRsnInf" type="StatusReasonInformation12">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">StatusReasonInformation</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Provides detailed information on the status reason.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">სტატუსის მიზეზის შესახებ დეტალური ინფორმაცია.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="4" minOccurs="0" name="ChrgsInf" type="GEO_Charges7">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">ChargesInformation</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">
						Provides information on the charges related to the processing of the rejection of the instruction.

						Usage: This is passed on for information purposes only. Settlement of the charges will be done separately.
					</xs:documentation>

				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="AccptncDtTm" type="GEO_ISODateTime">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">AcceptanceDateTime</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Point in time when the payment order from the initiating party meets the processing conditions of the account servicing agent. This means that the account servicing agent has received the payment order and has applied checks such as authorisation, availability of funds.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">წერტილი, როდესაც ინიციატორის მიერ გადახდის ბრძანება აკმაყოფილებს ანგარიშის მომსახურების აგენტის დამუშავების პირობებს. ეს ნიშნავს, რომ ანგარიშის მომსახურების აგენტმა მიიღო გადახდის ბრძანება და შეიტანა შემოწმებები, როგორიცაა ავტორიზაცია, თანხის ხელმისაწვდომობა.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GEO_StatusReason6Choice">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">GEO_StatusReason6Choice</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Specifies the reason for the status of the transaction.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">მიუთითებს ტრანზაქციის სტატუსის მიზეზს.</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="Cd" type="ExternalStatusReason1Code">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Reason for the status, as published in an external reason code list.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">სტატუსის მიზეზი, როგორც გამოქვეყნებულია გარე მიზეზების კოდების სიაში.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="StatusReasonInformation12">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">StatusReasonInformation12</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Provides detailed information on the status reason.</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">სტატუსის მიზეზის შესახებ დეტალური ინფორმაცია.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="0" name="Rsn" type="GEO_StatusReason6Choice">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">Reason</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">Specifies the reason for the status report.</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">მიუთითებს სტატუსის ანგარიშის მიზეზს.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element maxOccurs="4" minOccurs="0" name="AddtlInf" type="GEO_RestrictedFINXMax105Text_Ka">
				<xs:annotation>
					<xs:documentation source="Name" xml:lang="EN">AdditionalInformation</xs:documentation>
					<xs:documentation source="Definition" xml:lang="EN">
						Further details on the status reason.

						Usage: Additional information can be used for several purposes such as the reporting of repaired information.
					</xs:documentation>
					<xs:documentation source="Definition" xml:lang="KA">
						სტატუსის მიზეზის შესახებ დამატებითი დეტალები.

						გამოყენება: დამატებითი ინფორმაცია შეიძლება გამოყენებულ იქნას სხვადასხვა მიზნებისთვის, როგორიცაა შეკეთებული ინფორმაციის ანგარიშგება.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="UUIDv4Identifier">
		<xs:annotation>
			<xs:documentation source="Name" xml:lang="EN">UUIDv4Identifier</xs:documentation>
			<xs:documentation source="Definition" xml:lang="EN">Universally Unique Identifier (UUID) version 4, as described in c "Universally Unique IDentifier (UUID) URN Namespace".</xs:documentation>
			<xs:documentation source="Definition" xml:lang="KA">უნივერსალურად უნიკალური იდენტიფიკატორი (UUID) ვერსია 4, როგორც აღწერილია IETF RFC 4122-ში „Universally Unique IDentifier (UUID) URN Namespace“.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
